package com.project.megacitycab.util.exception;

public enum MegaCityCabExceptionType {
    // User Exceptions
    USER_NOT_FOUND,
    INVALID_USER_INPUTS,
    USER_ALREADY_EXISTS,
    INVALID_USER_CREDENTIALS,
    USER_NOT_ACTIVE,
    INVALID_USER_ROLE,
    CANNOT_CHANGE_EMAIL,

    // Driver Exceptions
    DRIVER_NOT_FOUND,
    DRIVER_ALREADY_EXISTS,
    DRIVER_LICENSE_INVALID,
    DRIVER_NOT_AVAILABLE,
    DRIVER_SUSPENDED,

    // Customer Exceptions
    CUSTOMER_NOT_FOUND,
    CUSTOMER_ALREADY_EXISTS,
    INVALID_CUSTOMER_INPUTS,
    CUSTOMER_EMAIL_ALREADY_EXISTS,
    CUSTOMER_NIC_ALREADY_EXISTS,
    CANNOT_CHANGE_REG_NO,

    // Vehicle Exceptions
    VEHICLE_NOT_FOUND,
    VEHICLE_ALREADY_REGISTERED,
    VEHICLE_NOT_AVAILABLE,
    VEHICLE_MAINTENANCE_REQUIRED,
    VEHICLE_TYPE_NOT_SUPPORTED,

    // Booking Exceptions
    BOOKING_NOT_FOUND,
    BOOKING_ALREADY_CANCELLED,
    BOOKING_PAYMENT_FAILED,
    BOOKING_NOT_ALLOWED,
    BOOKING_TIME_CONFLICT,

    // Bill Exceptions
    BILL_NOT_FOUND,
    BILL_ALREADY_PAID,
    BILL_GENERATION_FAILED,
    INVALID_BILL_DETAILS,

    // General System Exceptions
    PASSWORD_UTIL_EXCEPTION,
    SQL_EXCEPTION,
    INTERNAL_SERVER_ERROR
}
