name: CI/CD Pipeline
on:
  pull_request:
    branches:
      - stage
      - release
      - main

jobs:
  test-user-dao:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Fail if it takes too long
    services:
      mysql:
        image: mysql:8.0.36  # Specific version
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: mega_city_cab
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Initialize Database Schema
        run: |
          until mysql -h 127.0.0.1 -u root -p1234 -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done
          if [ -f "src/test/resources/schema.sql" ]; then
            mysql -h 127.0.0.1 -u root -p1234 mega_city_cab_test < src/test/resources/schema.sql
            echo "Database schema initialized successfully"
          else
            echo "Error: schema.sql not found in src/test/resources"
            exit 1
          fi
      - name: Run UserDaoImplTest
        run: mvn clean test -Dtest=UserDaoImplTest
      - name: Check Test Results
        if: always()
        run: |
          mvn test -Dtest=UserDaoImplTest
          if [ -d "target/surefire-reports" ]; then
            tar -czf surefire-reports.tar.gz target/surefire-reports/
            echo "Test reports archived as surefire-reports.tar.gz"
          fi
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: surefire-reports.tar.gz
          retention-days: 7
  # ... (rest of your jobs: merge-validation, build, deployment remain unchanged)
